/**
 * PDFGenerator - PDF 리포트 생성기
 * Business Brain 분석 결과를 PDF로 내보내기
 */

// jsPDF와 html2canvas는 동적 임포트로 처리
export interface ReportData {
  title: string
  subtitle?: string
  date: string
  summary: {
    keyMetrics: Array<{ label: string; value: string; change?: string }>
    highlights: string[]
    concerns: string[]
  }
  sections: Array<{
    title: string
    content: string
    chartId?: string
    tableData?: Array<Record<string, any>>
  }>
  insights: Array<{
    type: 'positive' | 'negative' | 'neutral'
    title: string
    description: string
    impact?: string
  }>
  actions: Array<{
    priority: 'high' | 'medium' | 'low'
    action: string
    expectedImpact: string
    timeline: string
  }>
  generatedBy: string
}

export interface PDFGeneratorOptions {
  orientation?: 'portrait' | 'landscape'
  format?: 'a4' | 'letter'
  includeCharts?: boolean
  includeWatermark?: boolean
  companyLogo?: string
}

export class PDFReportGenerator {
  private options: PDFGeneratorOptions

  constructor(options: PDFGeneratorOptions = {}) {
    this.options = {
      orientation: 'portrait',
      format: 'a4',
      includeCharts: true,
      includeWatermark: true,
      ...options,
    }
  }

  /**
   * 경영진 요약 리포트 생성
   */
  async generateExecutiveReport(data: ReportData): Promise<Blob> {
    // 동적 임포트
    const [{ default: jsPDF }, { default: html2canvas }] = await Promise.all([
      import('jspdf'),
      import('html2canvas'),
    ])

    const pdf = new jsPDF({
      orientation: this.options.orientation,
      unit: 'mm',
      format: this.options.format,
    })

    const pageWidth = pdf.internal.pageSize.getWidth()
    const pageHeight = pdf.internal.pageSize.getHeight()
    const margin = 20
    let yPosition = margin

    // 1. 표지
    await this.addCoverPage(pdf, data, pageWidth, pageHeight)

    // 2. 경영진 요약
    pdf.addPage()
    yPosition = margin
    yPosition = await this.addExecutiveSummary(pdf, data.summary, yPosition, pageWidth, margin)

    // 3. 핵심 인사이트
    pdf.addPage()
    yPosition = margin
    yPosition = await this.addInsightsSection(pdf, data.insights, yPosition, pageWidth, margin)

    // 4. 액션 아이템
    if (yPosition > pageHeight - 80) {
      pdf.addPage()
      yPosition = margin
    }
    yPosition = await this.addActionsSection(pdf, data.actions, yPosition, pageWidth, margin)

    // 5. 차트 섹션 (옵션)
    if (this.options.includeCharts && data.sections.length > 0) {
      for (const section of data.sections) {
        if (section.chartId) {
          pdf.addPage()
          await this.addChartSection(pdf, section.chartId, section.title, html2canvas)
        }
      }
    }

    // 워터마크
    if (this.options.includeWatermark) {
      this.addWatermark(pdf, data.generatedBy, pageWidth, pageHeight)
    }

    return pdf.output('blob')
  }

  /**
   * 표지 추가
   */
  private async addCoverPage(
    pdf: any,
    data: ReportData,
    pageWidth: number,
    pageHeight: number
  ): Promise<void> {
    // 배경 그라데이션 효과 (간단한 사각형으로 대체)
    pdf.setFillColor(99, 102, 241) // indigo-500
    pdf.rect(0, 0, pageWidth, pageHeight * 0.4, 'F')

    // 제목
    pdf.setTextColor(255, 255, 255)
    pdf.setFontSize(32)
    pdf.text(data.title, pageWidth / 2, pageHeight * 0.2, { align: 'center' })

    // 부제목
    if (data.subtitle) {
      pdf.setFontSize(16)
      pdf.text(data.subtitle, pageWidth / 2, pageHeight * 0.27, { align: 'center' })
    }

    // 날짜
    pdf.setTextColor(100, 100, 100)
    pdf.setFontSize(14)
    pdf.text(data.date, pageWidth / 2, pageHeight * 0.6, { align: 'center' })

    // 생성 정보
    pdf.setFontSize(10)
    pdf.text(`Generated by ${data.generatedBy}`, pageWidth / 2, pageHeight * 0.9, { align: 'center' })
  }

  /**
   * 경영진 요약 섹션 추가
   */
  private async addExecutiveSummary(
    pdf: any,
    summary: ReportData['summary'],
    startY: number,
    pageWidth: number,
    margin: number
  ): Promise<number> {
    let y = startY

    // 섹션 제목
    pdf.setTextColor(30, 41, 59) // slate-800
    pdf.setFontSize(20)
    pdf.text('Executive Summary', margin, y)
    y += 15

    // 핵심 지표
    pdf.setFontSize(14)
    pdf.text('Key Metrics', margin, y)
    y += 10

    const metricsPerRow = 3
    const metricWidth = (pageWidth - 2 * margin) / metricsPerRow

    summary.keyMetrics.forEach((metric, idx) => {
      const col = idx % metricsPerRow
      const row = Math.floor(idx / metricsPerRow)
      const x = margin + col * metricWidth
      const metricY = y + row * 25

      // 라벨
      pdf.setFontSize(9)
      pdf.setTextColor(100, 116, 139) // slate-500
      pdf.text(metric.label, x, metricY)

      // 값
      pdf.setFontSize(16)
      pdf.setTextColor(30, 41, 59)
      pdf.text(metric.value, x, metricY + 7)

      // 변화율
      if (metric.change) {
        pdf.setFontSize(10)
        const isPositive = metric.change.startsWith('+')
        pdf.setTextColor(isPositive ? 34 : 239, isPositive ? 197 : 68, isPositive ? 94 : 68)
        pdf.text(metric.change, x + 35, metricY + 7)
      }
    })

    y += Math.ceil(summary.keyMetrics.length / metricsPerRow) * 25 + 10

    // 하이라이트
    if (summary.highlights.length > 0) {
      pdf.setFontSize(14)
      pdf.setTextColor(30, 41, 59)
      pdf.text('Highlights', margin, y)
      y += 8

      pdf.setFontSize(10)
      pdf.setTextColor(71, 85, 105)
      summary.highlights.forEach(highlight => {
        pdf.text(`• ${highlight}`, margin + 5, y)
        y += 6
      })
      y += 5
    }

    // 주의 사항
    if (summary.concerns.length > 0) {
      pdf.setFontSize(14)
      pdf.setTextColor(30, 41, 59)
      pdf.text('Areas of Concern', margin, y)
      y += 8

      pdf.setFontSize(10)
      pdf.setTextColor(239, 68, 68)
      summary.concerns.forEach(concern => {
        pdf.text(`• ${concern}`, margin + 5, y)
        y += 6
      })
    }

    return y + 10
  }

  /**
   * 인사이트 섹션 추가
   */
  private async addInsightsSection(
    pdf: any,
    insights: ReportData['insights'],
    startY: number,
    pageWidth: number,
    margin: number
  ): Promise<number> {
    let y = startY

    pdf.setTextColor(30, 41, 59)
    pdf.setFontSize(20)
    pdf.text('Key Insights', margin, y)
    y += 15

    insights.forEach((insight, idx) => {
      // 아이콘/타입 표시
      const typeColors = {
        positive: [34, 197, 94],
        negative: [239, 68, 68],
        neutral: [100, 116, 139],
      }
      const color = typeColors[insight.type]
      pdf.setFillColor(color[0], color[1], color[2])
      pdf.circle(margin + 3, y - 2, 3, 'F')

      // 제목
      pdf.setFontSize(12)
      pdf.setTextColor(30, 41, 59)
      pdf.text(insight.title, margin + 10, y)
      y += 6

      // 설명
      pdf.setFontSize(10)
      pdf.setTextColor(71, 85, 105)
      const lines = pdf.splitTextToSize(insight.description, pageWidth - 2 * margin - 10)
      pdf.text(lines, margin + 10, y)
      y += lines.length * 5 + 3

      // 영향
      if (insight.impact) {
        pdf.setFontSize(9)
        pdf.setTextColor(100, 116, 139)
        pdf.text(`Impact: ${insight.impact}`, margin + 10, y)
        y += 5
      }

      y += 8
    })

    return y
  }

  /**
   * 액션 아이템 섹션 추가
   */
  private async addActionsSection(
    pdf: any,
    actions: ReportData['actions'],
    startY: number,
    pageWidth: number,
    margin: number
  ): Promise<number> {
    let y = startY

    pdf.setTextColor(30, 41, 59)
    pdf.setFontSize(20)
    pdf.text('Recommended Actions', margin, y)
    y += 15

    const priorityColors = {
      high: [239, 68, 68],
      medium: [245, 158, 11],
      low: [100, 116, 139],
    }

    actions.forEach((action, idx) => {
      // 우선순위 배지
      const color = priorityColors[action.priority]
      pdf.setFillColor(color[0], color[1], color[2])
      pdf.roundedRect(margin, y - 4, 15, 6, 1, 1, 'F')
      pdf.setFontSize(7)
      pdf.setTextColor(255, 255, 255)
      pdf.text(action.priority.toUpperCase(), margin + 2, y)

      // 액션
      pdf.setFontSize(11)
      pdf.setTextColor(30, 41, 59)
      pdf.text(action.action, margin + 20, y)
      y += 6

      // 예상 영향
      pdf.setFontSize(9)
      pdf.setTextColor(71, 85, 105)
      pdf.text(`Expected Impact: ${action.expectedImpact}`, margin + 20, y)
      y += 5

      // 타임라인
      pdf.text(`Timeline: ${action.timeline}`, margin + 20, y)
      y += 10
    })

    return y
  }

  /**
   * 차트 섹션 추가
   */
  private async addChartSection(
    pdf: any,
    elementId: string,
    title: string,
    html2canvas: any
  ): Promise<void> {
    const element = document.getElementById(elementId)
    if (!element) return

    const canvas = await html2canvas(element, { scale: 2 })
    const imgData = canvas.toDataURL('image/png')

    const pageWidth = pdf.internal.pageSize.getWidth()
    const margin = 20

    pdf.setFontSize(16)
    pdf.setTextColor(30, 41, 59)
    pdf.text(title, margin, margin)

    // 이미지 비율 계산
    const imgWidth = pageWidth - 2 * margin
    const imgHeight = (canvas.height * imgWidth) / canvas.width

    pdf.addImage(imgData, 'PNG', margin, margin + 10, imgWidth, Math.min(imgHeight, 150))
  }

  /**
   * 워터마크 추가
   */
  private addWatermark(
    pdf: any,
    text: string,
    pageWidth: number,
    pageHeight: number
  ): void {
    const pageCount = pdf.internal.getNumberOfPages()
    
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i)
      pdf.setFontSize(8)
      pdf.setTextColor(200, 200, 200)
      pdf.text(
        `${text} | Page ${i} of ${pageCount}`,
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      )
    }
  }

  /**
   * 간단한 데이터 리포트 생성
   */
  async generateDataReport(
    title: string,
    data: Array<Record<string, any>>,
    columns: Array<{ key: string; label: string }>
  ): Promise<Blob> {
    const { default: jsPDF } = await import('jspdf')

    const pdf = new jsPDF({
      orientation: 'landscape',
      unit: 'mm',
      format: 'a4',
    })

    const pageWidth = pdf.internal.pageSize.getWidth()
    const margin = 15
    let y = margin

    // 제목
    pdf.setFontSize(18)
    pdf.setTextColor(30, 41, 59)
    pdf.text(title, margin, y)
    y += 15

    // 테이블 헤더
    const colWidth = (pageWidth - 2 * margin) / columns.length
    
    pdf.setFillColor(241, 245, 249)
    pdf.rect(margin, y - 5, pageWidth - 2 * margin, 10, 'F')
    
    pdf.setFontSize(10)
    pdf.setTextColor(71, 85, 105)
    columns.forEach((col, idx) => {
      pdf.text(col.label, margin + idx * colWidth + 2, y)
    })
    y += 10

    // 테이블 데이터
    pdf.setFontSize(9)
    pdf.setTextColor(30, 41, 59)
    
    data.forEach((row, rowIdx) => {
      if (y > pdf.internal.pageSize.getHeight() - 20) {
        pdf.addPage()
        y = margin
      }

      // 줄무늬 배경
      if (rowIdx % 2 === 1) {
        pdf.setFillColor(248, 250, 252)
        pdf.rect(margin, y - 4, pageWidth - 2 * margin, 8, 'F')
      }

      columns.forEach((col, colIdx) => {
        const value = String(row[col.key] ?? '')
        const truncated = value.length > 25 ? value.substring(0, 22) + '...' : value
        pdf.text(truncated, margin + colIdx * colWidth + 2, y)
      })
      y += 8
    })

    return pdf.output('blob')
  }
}

// 싱글톤 인스턴스
export const pdfGenerator = new PDFReportGenerator()

