// lib/icon-mapping.ts
import { 
  // 기존
  TrendingUp, DollarSign, Package, Users, 
  BarChart3, PieChart, LineChart, Activity,
  AlertCircle, CheckCircle, XCircle, Info,
  // 추가
  Truck, Plane, Search, Brain, 
  Calendar, FileText, Settings, Download,
  Upload, Filter, RefreshCw, MoreVertical,
  Edit, Trash2, Eye, EyeOff, Lock, Unlock,
  Plus, Minus, X, ChevronRight, ChevronLeft,
  ArrowUp, ArrowDown, TrendingDown,
  Clock, Bell, Mail, Phone, MapPin,
  Globe, Flag, CreditCard, ShoppingCart,
  Star, Heart, Share2, Copy, Check,
  AlertTriangle, HelpCircle, Zap,
  Target, Award, Gift, Tag, Percent,
  Palette, Sparkles, BookOpen, Database,
  MessageCircle,
  BarChart, PieChart as PieChartIcon, LineChart as LineChartIcon
} from 'lucide-react'

export const iconMap = {
  // 기존 매핑
  revenue: DollarSign,
  orders: Package,
  customers: Users,
  growth: TrendingUp,
  barChart: BarChart3,
  pieChart: PieChart,
  lineChart: LineChart,
  activity: Activity,
  success: CheckCircle,
  error: XCircle,
  warning: AlertCircle,
  info: Info,
  
  // 추가 매핑
  logistics: Truck,
  shipping: Plane,
  search: Search,
  brain: Brain,
  calendar: Calendar,
  document: FileText,
  settings: Settings,
  download: Download,
  upload: Upload,
  filter: Filter,
  refresh: RefreshCw,
  more: MoreVertical,
  edit: Edit,
  delete: Trash2,
  view: Eye,
  hide: EyeOff,
  lock: Lock,
  unlock: Unlock,
  add: Plus,
  remove: Minus,
  close: X,
  next: ChevronRight,
  prev: ChevronLeft,
  up: ArrowUp,
  down: ArrowDown,
  decline: TrendingDown,
  time: Clock,
  notification: Bell,
  email: Mail,
  phone: Phone,
  location: MapPin,
  global: Globe,
  country: Flag,
  payment: CreditCard,
  cart: ShoppingCart,
  star: Star,
  favorite: Heart,
  share: Share2,
  copy: Copy,
  check: Check,
  alert: AlertTriangle,
  help: HelpCircle,
  lightning: Zap,
  target: Target,
  award: Award,
  gift: Gift,
  tag: Tag,
  discount: Percent,
  palette: Palette,
  sparkles: Sparkles,
  book: BookOpen,
  database: Database,
  messageCircle: MessageCircle,
} as const

// 이모지 → 아이콘 매핑 테이블 (완전판)
export const emojiToIconMap: Record<string, keyof typeof iconMap> = {
  '📊': 'barChart',
  '💰': 'revenue',
  '📦': 'orders',
  '👥': 'customers',
  '📈': 'growth',
  '🚨': 'alert',
  '✅': 'success',
  '🔍': 'search',
  '🚚': 'logistics',
  '✈️': 'shipping',
  '🧠': 'brain',
  '📅': 'calendar',
  '📄': 'document',
  '⚙️': 'settings',
  '⬇️': 'download',
  '⬆️': 'upload',
  '🔽': 'filter',
  '🔄': 'refresh',
  '⋮': 'more',
  '✏️': 'edit',
  '🗑️': 'delete',
  '👁️': 'view',
  '🔒': 'lock',
  '🔓': 'unlock',
  '➕': 'add',
  '➖': 'remove',
  '❌': 'close',
  '▶️': 'next',
  '◀️': 'prev',
  '📉': 'decline',
  '⏰': 'time',
  '🔔': 'notification',
  '📧': 'email',
  '📞': 'phone',
  '📍': 'location',
  '🌐': 'global',
  '🏳️': 'country',
  '💳': 'payment',
  '🛒': 'cart',
  '⭐': 'star',
  '❤️': 'favorite',
  '🔗': 'share',
  '📋': 'copy',
  '✓': 'check',
  '⚠️': 'warning',
  '❓': 'help',
  '⚡': 'lightning',
  '🎯': 'target',
  '🏆': 'award',
  '🎁': 'gift',
  '🏷️': 'tag',
  '💯': 'discount',
  '🎨': 'palette',
  '✨': 'sparkles',
  '📚': 'book',
  '💾': 'database',
  '📡': 'activity',
  '👨‍🎨': 'palette',
  '📝': 'document',
  '🎟️': 'gift',
  '💬': 'messageCircle',
  '🔎': 'search',
}

